title: Kanglin Connie Chen
logo:  # you can add own logo.
description:
baseurl: ""
url: https://kanglin-chen.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Kanglin Chen
  image: '/assets/img/me.jpg'
  job: Welcome to my 'still under construction' page!
  bio: |+
    <br />
    I'm currently a PhD Student at UF.
    <br />
    <br />
    I am broadly interested in developing xxx tools for xxx applications relevant to public policy.
    I previously worked in xxx with a brief stint at the CA State Government.
    I hope to use my skills to somehow benefit society.
    <br />
    <br />
    This site is a blend of professional/personal content.
    <br />
  resume: https://kanglin-chen.github.io/assets/cv.pdf # https://drive.google.com/file/d/1Lr_RPlSyJhZZ1bWD8NxS_Ek1CBMjRqEL/view?usp=sharing
  email: kanglinchen@fas.harvard.edu
  github: https://github.com/kanglin-chen
  linkedin: https://www.linkedin.com/in/kanglinchen/
  last_update: August, 2023



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: sho-personal # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
