title: Kanglin Connie Chen
logo:  # you can add own logo.
description:
baseurl: ""
url: https://kanglin-chen.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Connie (Kanglin) Chen, Ph.D., M.S.
  image: '/assets/img/Connie.jpg'
  job: Preceptor in Geospatial Analysis
  bio: |+
    <font size="+1">
    <br />
    I am a preceptor (lecturer) in spatial analysis in the <a href="https://www.gov.harvard.edu/directory/kanglin-connie-chen/"> Government Department</a> 
    at Harvard University and an associate with <a href="https://gis.harvard.edu/"> Harvard's Center for Geographic Analysis (CGA)</a>. I teach introductory and advanced GIS, other spatial analysis-related courses, and GIS training programs.
    <br />
    <br />
    <a href="https://kanglin-chen.github.io/about/"> <u>Know more</u></a> 
    </font>
  resume: https://kanglin-chen.github.io/assets/cv.pdf # https://drive.google.com/file/d/1L.....
  email: kanglinchen@fas.harvard.edu
  github: https://github.com/kanglin-chen
  linkedin: https://www.linkedin.com/in/kanglinchen/
  last_update: July, 2024



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: conniechen # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
