title: Kanglin Connie Chen
logo:  # you can add own logo.
description:
baseurl: ""
url: https://kanglin-chen.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Connie (Kanglin) Chen
  image: '/assets/img/Connie.jpg'
  job: Welcome to my 'still under construction' page!
  bio: |+
    <br />
    I am a preceptor in spatial analysis in the Government Department at Harvard University and an associate with Harvard's Center for Geographic Analysis (CGA). I teach introductory and advanced GIS, other spatial analysis-related courses, and a GIS training program.
    <br />
    <br />
    I have a Ph.D. in Urban and Regional Planning, an MS in Geography (Urban and Regional Planning), and a Bachelor's degree in Landscape Gardening. 
    <br />
    My research fields include GIScience, travel behavior, social vulnerability and resilience, and the built environment. My primary research methods include spatial and statistical analysis, 3D geospatial techniques, and data mining.
    <br />
    I am proficient in GIS software, R, and Python programming languages. I also have training in qualitative methods and urban and landscape design. 
    <br />
    I have participated in environment-related research and practical projects in both the U.S. and China. 
    <br />
    I consider myself as a social-technological scholar.

    <br />
    <br />
    <br />
    This site is a blend of professional/personal content.
    <br />
  resume: https://kanglin-chen.github.io/assets/cv.pdf # https://drive.google.com/file/d/1Lr_RPlSyJhZZ1bWD8NxS_Ek1CBMjRqEL/view?usp=sharing
  email: kanglinchen@fas.harvard.edu
  github: https://github.com/kanglin-chen
  linkedin: https://www.linkedin.com/in/kanglinchen/
  last_update: August, 2023



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: sho-personal # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
